### ISSUE TITLE
`graph init` crashes when creating `substreams` subgraph

### ISSUE THREAD

**Issue by YaroShkvorets** [graphprotocol/graph-tooling#1087]
### Which packages are impacted by your issue?

@graphprotocol/graph-cli

### Describe the issue

Not able to create subgraph scaffolding with `graph init` when selecting `substreams` protocol.
Getting this error:

```
➜ graph init
✔ Protocol · substreams
✔ Product for which to initialize · subgraph-studio
✔ Subgraph slug · test/test
✔ Directory to create the subgraph in · test
/Users/shkvo/.nvm/versions/node/v18.13.0/lib/node_modules/@graphprotocol/graph-cli/node_modules/gluegun/build/index.js:13
    throw up;
    ^

TypeError: availableNetworks.get(...).toArray is not a function
    at SelectPrompt.choices (/Users/shkvo/.nvm/versions/node/v18.13.0/lib/node_modules/@graphprotocol/graph-cli/dist/commands/init.js:365:22)
    at toChoices (/Users/shkvo/.nvm/versions/node/v18.13.0/lib/node_modules/@graphprotocol/graph-cli/node_modules/enquirer/lib/types/array.js:66:60)
    at SelectPrompt.toChoices (/Users/shkvo/.nvm/versions/node/v18.13.0/lib/node_modules/@graphprotocol/graph-cli/node_modules/enquirer/lib/types/array.js:80:12)
    at SelectPrompt.reset (/Users/shkvo/.nvm/versions/node/v18.13.0/lib/node_modules/@graphprotocol/graph-cli/node_modules/enquirer/lib/types/array.js:34:49)
    at SelectPrompt.initialize (/Users/shkvo/.nvm/versions/node/v18.13.0/lib/node_modules/@graphprotocol/graph-cli/node_modules/enquirer/lib/types/array.js:25:16)
    at /Users/shkvo/.nvm/versions/node/v18.13.0/lib/node_modules/@graphprotocol/graph-cli/node_modules/enquirer/lib/prompt.js:236:18
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.13.0
```

### Reproduction

See steps below

### Steps to Reproduce the Bug or Issue

1. run `graph init`
2. select `substreams`
3. select `subgraph-studio`
4. type any slug
5. get error above

### Expected behavior

As a user, I'm expecting graph cli to generate scaffolding for my subgraph, but I'm getting an error

### Platform

- OS: `macOS`
- NodeJS: `18.13.0`
- `@graphprotocol/*` version(s): `@graphprotocol/graph-cli/0.41.1 darwin-arm64 node-v18.13.0`

**Comment by YaroShkvorets** [comment]
Pushed a PR to address it: https://github.com/graphprotocol/graph-tooling/pull/1129
