### ISSUE TITLE
Unable to compile past graph-cli 0.37.0

### ISSUE THREAD

**Issue by 0xged** [graphprotocol/graph-tooling#1212]
### Which packages are impacted by your issue?

@graphprotocol/graph-cli

### Describe the issue

Updating to any version higher than 0.37.0 breaks down the compilation. I've tried tracking down if there was any part of the code that was breaking the compilation but was not able to find any.

### Reproduction

https://github.com/Mean-Finance/dca-subgraph/tree/feat/update-graph

### Steps to Reproduce the Bug or Issue

When running `graph deploy` it breaks down, so executing `yarn deploy:optimism` it will throw:

```bash
Whoops, the AssemblyScript compiler has crashed during compile :-(

Here is the stack trace hinting at the problem, perhaps it's useful?

AssertionError: assertion failed
    at i.assert (/Users/{user}/projects/dca/dca-subgraph/node_modules/@graphprotocol/graph-cli/node_modules/assemblyscript/dist/assemblyscript.js:7:765506)
    at f.compileBinaryOverload (/Users/{user}/projects/dca/dca-subgraph/node_modules/@graphprotocol/graph-cli/node_modules/assemblyscript/dist/assemblyscript.js:7:280159)
    at f.compileBinaryExpression (/Users/{user}/projects/dca/dca-subgraph/node_modules/@graphprotocol/graph-cli/node_modules/assemblyscript/dist/assemblyscript.js:7:261152)
    at f.compileExpression (/Users/{user}/projects/dca/dca-subgraph/node_modules/@graphprotocol/graph-cli/node_modules/assemblyscript/dist/assemblyscript.js:7:245493)
    at f.compileAssignment (/Users/{user}/projects/dca/dca-subgraph/node_modules/@graphprotocol/graph-cli/node_modules/assemblyscript/dist/assemblyscript.js:7:282422)
    at f.compileBinaryExpression (/Users/{user}/projects/dca/dca-subgraph/node_modules/@graphprotocol/graph-cli/node_modules/assemblyscript/dist/assemblyscript.js:7:255392)
    at f.compileExpression (/Users/{user}/projects/dca/dca-subgraph/node_modules/@graphprotocol/graph-cli/node_modules/assemblyscript/dist/assemblyscript.js:7:245493)
    at f.compileExpressionStatement (/Users/{user}/projects/dca/dca-subgraph/node_modules/@graphprotocol/graph-cli/node_modules/assemblyscript/dist/assemblyscript.js:7:234314)
    at f.compileStatement (/Users/{user}/projects/dca/dca-subgraph/node_modules/@graphprotocol/graph-cli/node_modules/assemblyscript/dist/assemblyscript.js:7:230686)
    at f.compileStatements (/Users/{user}/projects/dca/dca-subgraph/node_modules/@graphprotocol/graph-cli/node_modules/assemblyscript/dist/assemblyscript.js:7:231714)

If it refers to the dist files, try to 'npm install source-map-support' and
run again, which should then show the actual code location in the sources.

If you see where the error is, feel free to send us a pull request. If not,
please let us know: https://github.com/AssemblyScript/assemblyscript/issues

Thank you!

✖ Failed to compile subgraph: Failed to compile data source mapping: The AssemblyScript compiler crashed when compiling this file: 'src/mappings/permissionsManager.ts'
Suggestion: try to comment the whole file and uncomment it little by little while re-running the graph-cli until you isolate the line where the problem happens.
Also, please contact us so we can make the CLI better by handling errors like this. You can reach out in any of these links:
- Discord channel: https://discord.gg/eM8CA6WA9r
- Github issues: https://github.com/graphprotocol/graph-cli/issues
Error: Failed to compile data source mapping: The AssemblyScript compiler crashed when compiling this file: 'src/mappings/permissionsManager.ts'
Suggestion: try to comment the whole file and uncomment it little by little while re-running the graph-cli until you isolate the line where the problem happens.
Also, please contact us so we can make the CLI better by handling errors like this. You can reach out in any of these links:
- Discord channel: https://discord.gg/eM8CA6WA9r
- Github issues: https://github.com/graphprotocol/graph-cli/issues
    at Compiler._compileDataSourceMapping (/Users/{user}/projects/dca/dca-subgraph/node_modules/@graphprotocol/graph-cli/src/compiler/index.js:320:13)
    at /Users/{user}/projects/dca/dca-subgraph/node_modules/@graphprotocol/graph-cli/src/compiler/index.js:224:20
    at updateInDeepMap (/Users/{user}/projects/dca/dca-subgraph/node_modules/immutable/dist/immutable.js:1971:22)
    at updateInDeepMap (/Users/{user}/projects/dca/dca-subgraph/node_modules/immutable/dist/immutable.js:1980:23)
    at updateInDeepMap (/Users/{user}/projects/dca/dca-subgraph/node_modules/immutable/dist/immutable.js:1980:23)
    at Map.updateIn (/Users/{user}/projects/dca/dca-subgraph/node_modules/immutable/dist/immutable.js:1278:26)
    at /Users/{user}/projects/dca/dca-subgraph/node_modules/@graphprotocol/graph-cli/src/compiler/index.js:223:24
    at /Users/{user}/projects/dca/dca-subgraph/node_modules/immutable/dist/immutable.js:3016:46
    at List.__iterate (/Users/{user}/projects/dca/dca-subgraph/node_modules/immutable/dist/immutable.js:2206:13)
    at mappedSequence.__iterateUncached (/Users/{user}/projects/dca/dca-subgraph/node_modules/immutable/dist/immutable.js:3015:23)
UNCAUGHT EXCEPTION: Error: The AssemblyScript compiler crashed when compiling this file: 'src/mappings/permissionsManager.ts'
Suggestion: try to comment the whole file and uncomment it little by little while re-running the graph-cli until you isolate the line where the problem happens.```

### Expected behavior

To compile and deploy the subgraph successfully.

### Screenshots or Videos

_No response_

### Platform

- OS: macOS
- NodeJS: v18.12.1
- "@graphprotocol/graph-cli": "0.37.1"
- "@graphprotocol/graph-ts": "0.29.3"


### Subgraph Manifest

_No response_

### Subgraph GraphQL Schema

_No response_

### Additional context

_No response_

**Comment by 0xged** [comment]
@azf20 yeap, it does. I had `0.34.x` version, and kept bumping version by version, until I understood what version exactly broke down the compilation.

**Comment by schmidsi** [comment]
I ran into a similar problem while upgrading a subgraph. One problem that I identified was type breaking comparisons: https://github.com/arr00/uniswap-governance-subgraph-v2/compare/master...schmidsi:uniswap-governance-subgraph-v2:master#diff-4fa4aa0fca512c5a712612b648497e213fb60672b926de2ab0c7396a230cf565R364. But I'm not fully done yet.

**Comment by 0xged** [comment]
> I ran into a similar problem while upgrading a subgraph. One problem that I identified was type breaking comparisons: [arr00/uniswap-governance-subgraph-v2@master...schmidsi:uniswap-governance-subgraph-v2:master#diff-4fa4aa0fca512c5a712612b648497e213fb60672b926de2ab0c7396a230cf565R364](https://github.com/arr00/uniswap-governance-subgraph-v2/compare/master...schmidsi:uniswap-governance-subgraph-v2:master#diff-4fa4aa0fca512c5a712612b648497e213fb60672b926de2ab0c7396a230cf565R364). But I'm not fully done yet.

Hey, thanks for the info -- sadly, I've changed all reference to `.toHexString()` to `toString()` and it still doesn't compile.

**Comment by 0xged** [comment]
I found the issue had to do with an explicity bit shifting on `BigInt` instead of using `leftShit` and `rightShift` - still, it's clear that assembly script compilation errors are pretty bad. Hopefully they get better in the future.
