### ISSUE TITLE
Can't install prior versions of graph-cli depending on https://github.com/hugomrdias/concat-stream.git branch feat/smaller

### ISSUE THREAD

**Issue by Eduard-Voiculescu** [graphprotocol/graph-tooling#1323]
### Which packages are impacted by your issue?

@graphprotocol/graph-cli

### Describe the issue

```bash
$> yarn global add @graphprotocol/graph-cli@0.30.1                                                                                                                      
yarn global v1.22.18
[1/4] 🔍  Resolving packages...
warning @graphprotocol/graph-cli > debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
warning @graphprotocol/graph-cli > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @graphprotocol/graph-cli > ipfs-http-client > cids@0.7.5: This module has been superseded by the multiformats module
warning @graphprotocol/graph-cli > ipfs-http-client > ipld-dag-pb@0.17.4: This module has been superseded by @ipld/dag-pb and multiformats
warning @graphprotocol/graph-cli > ipfs-http-client > ipld-raw@4.0.1: This module has been superseded by the multiformats module
warning @graphprotocol/graph-cli > ipfs-http-client > ipld-dag-cbor@0.15.3: This module has been superseded by @ipld/dag-cbor and multiformats
warning @graphprotocol/graph-cli > ipfs-http-client > multicodec@0.5.7: This module has been superseded by the multiformats module
warning @graphprotocol/graph-cli > ipfs-http-client > ipld-dag-pb > multicodec@0.5.7: This module has been superseded by the multiformats module
warning @graphprotocol/graph-cli > ipfs-http-client > multiaddr@6.1.1: This module is deprecated, please upgrade to @multiformats/multiaddr
warning @graphprotocol/graph-cli > ipfs-http-client > peer-info@0.15.1: No longer supported for js-libp2p0.28.0 or later
warning @graphprotocol/graph-cli > ipfs-http-client > ipld-dag-pb > multihashing-async@0.7.0: This module has been superseded by the multiformats module
warning @graphprotocol/graph-cli > ipfs-http-client > ipld-raw > multihashing-async@0.8.2: This module has been superseded by the multiformats module
warning @graphprotocol/graph-cli > ipfs-http-client > ipld-dag-cbor > multihashing-async@0.8.2: This module has been superseded by the multiformats module
error Command failed.
Exit code: 1
Command: git
Arguments: pull
Directory: /Users/eduardvoiculescu/Library/Caches/Yarn/v6/.tmp/166c4037ddf7608d79e84e263dcd7746
Output:
Your configuration specifies to merge with the ref 'refs/heads/master'
from the remote, but no such ref was fetched.
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
Error: Couldn't find match for "feat/smaller" in "refs/heads/1.3.x,refs/heads/1.4.x,refs/heads/master,refs/tags/v1.3.2,refs/tags/v1.4.10,refs/tags/v1.4.11,refs/tags/v1.4.7,refs/tags/v1.4.8,refs/tags/v1.4.9,refs/tags/v1.5.0,refs/tags/v1.5.1,refs/tags/v1.5.2,refs/tags/v1.6.0,refs/tags/v1.6.1,refs/tags/v1.6.2,refs/tags/v2.0.0" for "https://github.com/hugomrdias/concat-stream.git".
    at MessageError.ExtendableBuiltin (/opt/homebrew/Cellar/yarn/1.22.18/libexec/lib/cli.js:721:66)
    at new MessageError (/opt/homebrew/Cellar/yarn/1.22.18/libexec/lib/cli.js:750:123)
    at Git.<anonymous> (/opt/homebrew/Cellar/yarn/1.22.18/libexec/lib/cli.js:51238:15)
    at Generator.next (<anonymous>)
    at step (/opt/homebrew/Cellar/yarn/1.22.18/libexec/lib/cli.js:310:30)
    at /opt/homebrew/Cellar/yarn/1.22.18/libexec/lib/cli.js:321:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Reproduction

Please read below

### Steps to Reproduce the Bug or Issue

`npm install -g @graphprotocol/graph-cli@0.31.0`
of 
`yarn global add @graphprotocol/graph-cli@0.30.1`

### Expected behavior

I expect to be able to download a prior version of graph-cli. Notably to deploy a subgraph locally which contains a version of the `mapping` of `apiVersion: 0.0.4`.

### Platform

- OS: macOS M1
- NodeJS: v16.13.1
- `@graphprotocol/*` version(s): 0.30.1

**Comment by jmilldotdev** [comment]
+1, come on.

**Comment by saihaj** [comment]
Hey this is an underlying dependency issue. We use IPFS client which further used a dependency which was from a GitHub repository. The author of that repo made some changes which broke many client.

If you are using yarn or pnpm you can overwrite to use a fork of that dependency as done here https://github.com/graphprotocol/graph-tooling/issues/1264#issuecomment-1501457669

Obviously it is better if you can upgrade to latest version :)
