### ISSUE TITLE
Compile subgraphERROR TS2718: Duplicate property 'id'

### ISSUE THREAD

**Issue by Madeindreams** [graphprotocol/graph-tooling#710]
First time I compiled my ProxyAdminUpgradeable.
Then I tried with the implementation address and got this error.

Seems to be complaining about a BN
```
 Compile subgraphERROR TS2718: Duplicate property 'id'.

   get id(): BigInt {
       ~~
 in generated/schema.ts(54,6)

ERROR TS2718: Duplicate property 'id'.

   set id(value: BigInt) {
       ~~
 in generated/schema.ts(59,6)


ERROR AS200: Conversion from type '~lib/@graphprotocol/graph-ts/index/BigInt' to '~lib/string/String' requires an explicit cast.

   entity.id = event.params.id
               ~~~~~~~~~~~~~~~
 in src/mapping.ts(26,14)

✖ Failed to compile subgraph: Failed to compile data source mapping: Compile error
Error: Failed to compile data source mapping: Compile error
    at Compiler._compileDataSourceMapping (/home/ian/code/graph/comp/node_modules/@graphprotocol/graph-cli/src/compiler.js:314:13)
    at /home/ian/code/graph/comp/node_modules/@graphprotocol/graph-cli/src/compiler.js:207:20
    at updateInDeepMap (/home/ian/code/graph/comp/node_modules/immutable/dist/immutable.js:1971:22)
    at updateInDeepMap (/home/ian/code/graph/comp/node_modules/immutable/dist/immutable.js:1980:23)
    at updateInDeepMap (/home/ian/code/graph/comp/node_modules/immutable/dist/immutable.js:1980:23)
    at Map.updateIn (/home/ian/code/graph/comp/node_modules/immutable/dist/immutable.js:1278:26)
    at /home/ian/code/graph/comp/node_modules/@graphprotocol/graph-cli/src/compiler.js:206:24
    at /home/ian/code/graph/comp/node_modules/immutable/dist/immutable.js:3016:46
    at List.__iterate (/home/ian/code/graph/comp/node_modules/immutable/dist/immutable.js:2206:13)
    at IndexedIterable.mappedSequence.__iterateUncached (/home/ian/code/graph/comp/node_modules/immutable/dist/immutable.js:3015:23)

```

**Comment by maxisacoder** [comment]
still there

**Comment by pedrohba1** [comment]
It happens because you have `id` properties in your events and the auto generated code has tem too by default.


Change your contract events from something like this:

```js
  event IncorporateStart(uint256 indexed id, address incorporator);
```

to this: 

```js
  event IncorporateStart(uint256 indexed itemId, address incorporator);
``` 

and it should stop complaining when you run `build`. You should do the same change on every contract that emits an `id` 

At least that is the solution that worked for me so far.

**Comment by richardryangarcia** [comment]
Is there a temporary work around to this that does not include updating the contract event signature?
