### ISSUE TITLE
Install broken for yarn v2 projects

### ISSUE THREAD

**Issue by carlosdp** [graphprotocol/graph-tooling#814]
This commit https://github.com/graphprotocol/graph-cli/commit/45f0ac14ad55e249def5c7e7776c6c98e1a1cedc seems to have broken installs for projects using yarn v2.

It looks like it is related to an issue yarn has with some git refs for dependencies potentially: https://github.com/yarnpkg/berry/issues/3194 . Pinning to version `0.25.1` fixed the issue for me.

My recommendation is to publish the changes to the `gluegun` package to npm and reference it there instead of using a git ref so we can avoid this error! I would submit a PR myself, but I can't publish the package for you, unfortunately 😄 

Edit: to be clear, this is using node_modules linking, not pnp

**Comment by tuler** [comment]
Maybe I bumped into this same issue.
When I run `graph test` from a yarn 2 project (yarn 3.1.1 actually) I get this error:

```
<project_root>/.yarn/cache/gluegun-https-7779acd458-872685026d.zip/node_modules/gluegun/build/index.js:13
    throw up;
    ^

Error: @graphprotocol/graph-cli tried to access strip-ansi, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: strip-ansi
Required by: @graphprotocol/graph-cli@npm:0.25.3 (via <project_root>/.yarn/unplugged/@graphprotocol-graph-cli-npm-0.25.3-3a1b82a50e/node_modules/@graphprotocol/graph-cli/src/commands/)

Require stack:
- <project_root>/.yarn/unplugged/@graphprotocol-graph-cli-npm-0.25.3-3a1b82a50e/node_modules/@graphprotocol/graph-cli/src/commands/local.js
- <project_root>/.yarn/cache/gluegun-https-7779acd458-872685026d.zip/node_modules/gluegun/build/loaders/module-loader.js
- <project_root>/.yarn/cache/gluegun-https-7779acd458-872685026d.zip/node_modules/gluegun/build/loaders/command-loader.js
- <project_root>/.yarn/cache/gluegun-https-7779acd458-872685026d.zip/node_modules/gluegun/build/runtime/runtime.js
- <project_root>/.yarn/cache/gluegun-https-7779acd458-872685026d.zip/node_modules/gluegun/build/domain/builder.js
- <project_root>/.yarn/cache/gluegun-https-7779acd458-872685026d.zip/node_modules/gluegun/build/index.js
- <project_root>/.yarn/unplugged/@graphprotocol-graph-cli-npm-0.25.3-3a1b82a50e/node_modules/@graphprotocol/graph-cli/src/cli.js
- <project_root>/.yarn/unplugged/@graphprotocol-graph-cli-npm-0.25.3-3a1b82a50e/node_modules/@graphprotocol/graph-cli/bin/graph
    at Function.external_module_.Module._resolveFilename (<project_root>/.pnp.cjs:19038:55)
    at Function.external_module_.Module._load (<project_root>/.pnp.cjs:18837:48)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (<project_root>/.yarn/unplugged/@graphprotocol-graph-cli-npm-0.25.3-3a1b82a50e/node_modules/@graphprotocol/graph-cli/src/commands/local.js:8:19)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.external_module_.Module._load (<project_root>/.pnp.cjs:18887:14)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
```

**Comment by carlosdp** [comment]
Not the same error I was getting, but it's related to the same dependency (gluegun)

**Comment by tuler** [comment]
I found out it's related to a missing dependency to `strip-ansi`.
I had to configured this in my `.yarnrc.yaml`. (then bumped into another [yarn related problem](https://github.com/graphprotocol/graph-cli/issues/815)).

```
packageExtensions:
    "@graphprotocol/graph-cli@*":
        dependencies:
            "strip-ansi": "5.2.0"
```

**Comment by carlosdp** [comment]
Yea, so unrelated to this issue then 😄

**Comment by azf20** [comment]
Hey @carlosdp thanks for reporting! @otaviopace I think this was maybe fixed since the upstream accepted your PR?

**Comment by saihaj** [comment]
is this still an issue?
