### ISSUE TITLE
Running `yarn test` yields "Jest did not exit one second after the test run has completed"

### ISSUE THREAD

**Issue by dimitrovmaksim** [graphprotocol/graph-tooling#849]
When running yarn test, jest does not exit, but if I run every test suite separately it exits correctly

```
Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  PROCESSWRAP

      at Process.emitInitNative (node:internal/async_hooks:205:43)
      at new ChildProcess (node:internal/child_process:263:18)
      at spawn (node:child_process:695:17)
      at start (node_modules/sync-rpc/lib/index.js:33:13)
      at sendMessage (node_modules/sync-rpc/lib/index.js:133:17)
      at createClient (node_modules/sync-rpc/lib/index.js:173:27)
      at Object.<anonymous> (node_modules/sync-request/lib/index.js:16:14)
```

```
yarn -v
1.22.17
```

**Comment by otaviopace** [comment]
Just as a note, I've had the same experience with `yarn` version `1.22.10`.

**Comment by saihaj** [comment]
Yes I created https://github.com/graphprotocol/graph-tooling/issues/1086
